const errorCodes = {
  ERR_CODE_CONTINUE: 'ERR_CODE_CONTINUE',
  ERR_CODE_INTERNAL_SERVER_ERROR: 'ERR_CODE_INTERNAL_SERVER_ERROR',
  ERR_CODE_RESOURCE_CONFLICT: 'ERR_CODE_RESOURCE_CONFLICT',
  ERR_CODE_RESOURCE_FORBIDDEN: 'ERR_CODE_RESOURCE_FORBIDDEN',
  ERR_CODE_RESOURCE_NOT_FOUND: 'ERR_CODE_RESOURCE_NOT_FOUND',
  ERR_CODE_TOO_MANY_REQUESTS: 'ERR_CODE_TOO_MANY_REQUESTS',
  ERR_CODE_UNAUTHORIZED: 'ERR_CODE_UNAUTHORIZED',
  ERR_CODE_UNPROCESSABLE_ENTITY: 'ERR_CODE_UNPROCESSABLE_ENTITY',
  ERR_CODE_VALIDATION_ERROR: 'ERR_CODE_VALIDATION_ERROR'
};

module.exports = errorCodes;
